export interface LocationData {
  slug: string;
  name: string;
  city: string;
  state: string;
  postalCode: string;
  lat: number;
  lng: number;
  description: string;
  reviewCount: number;
  areas: string[];
}

export const locations: LocationData[] = [
  { slug: 'agra', name: 'Agra', city: 'Agra', state: 'Uttar Pradesh', postalCode: '282001', lat: 27.1767, lng: 78.0081, description: 'Premium escorts in Agra available 24/7.', reviewCount: 87, areas: ['Taj Mahal Area', 'Civil Lines', 'Sikandra', 'Fatehabad Road'] },
  { slug: 'ahmedabad', name: 'Ahmedabad', city: 'Ahmedabad', state: 'Gujarat', postalCode: '380001', lat: 23.0225, lng: 72.5714, description: 'Premium escorts in Ahmedabad available 24/7.', reviewCount: 134, areas: ['SG Road', 'Navrangpura', 'CG Road', 'Vastrapur'] },
  { slug: 'airoli', name: 'Airoli', city: 'Airoli', state: 'Maharashtra', postalCode: '400708', lat: 19.1567, lng: 72.9989, description: 'Premium escorts in Airoli available 24/7.', reviewCount: 56, areas: ['Airoli Sector 1', 'Airoli Sector 3', 'Airoli Sector 5', 'Airoli Station'] },
  { slug: 'ambernath', name: 'Ambernath', city: 'Ambernath', state: 'Maharashtra', postalCode: '421501', lat: 19.2002, lng: 73.1793, description: 'Premium escorts in Ambernath available 24/7.', reviewCount: 43, areas: ['Ambernath West', 'Ambernath East', 'Shivaji Nagar'] },
  { slug: 'ambivali', name: 'Ambivali', city: 'Ambivali', state: 'Maharashtra', postalCode: '421102', lat: 19.2167, lng: 73.2000, description: 'Premium escorts in Ambivali available 24/7.', reviewCount: 32, areas: ['Ambivali Station', 'Shirgaon'] },
  { slug: 'andheri', name: 'Andheri', city: 'Andheri', state: 'Maharashtra', postalCode: '400053', lat: 19.1136, lng: 72.8697, description: 'Premium escorts in Andheri available 24/7. One of Mumbai\'s most vibrant suburbs.', reviewCount: 196, areas: ['Andheri East', 'Andheri West', 'Versova', 'Jogeshwari', 'Lokhandwala', 'Oshiwara'] },
  { slug: 'asangaon', name: 'Asangaon', city: 'Asangaon', state: 'Maharashtra', postalCode: '421601', lat: 19.5167, lng: 73.1833, description: 'Premium escorts in Asangaon available 24/7.', reviewCount: 28, areas: ['Asangaon Station', 'Village Area'] },
  { slug: 'baba', name: 'Baba', city: 'Baba', state: 'Maharashtra', postalCode: '401202', lat: 19.5500, lng: 73.0000, description: 'Premium escorts in Baba available 24/7.', reviewCount: 21, areas: ['Baba Station Area'] },
  { slug: 'badlapur', name: 'Badlapur', city: 'Badlapur', state: 'Maharashtra', postalCode: '421503', lat: 19.1573, lng: 73.2637, description: 'Premium escorts in Badlapur available 24/7.', reviewCount: 47, areas: ['Badlapur East', 'Badlapur West', 'Manjarli'] },
  { slug: 'bandra', name: 'Bandra', city: 'Bandra', state: 'Maharashtra', postalCode: '400050', lat: 19.0596, lng: 72.8295, description: 'Premium escorts in Bandra - Mumbai\'s most upscale suburb. Queen of Suburbs.', reviewCount: 218, areas: ['Bandra West', 'Bandra East', 'Khar', 'Santacruz', 'Linking Road', 'Carter Road'] },
  { slug: 'bangalore', name: 'Bangalore', city: 'Bangalore', state: 'Karnataka', postalCode: '560001', lat: 12.9716, lng: 77.5946, description: 'Premium escorts in Bangalore available 24/7.', reviewCount: 312, areas: ['Koramangala', 'Indiranagar', 'Whitefield', 'MG Road', 'HSR Layout', 'Jayanagar'] },
  { slug: 'belapur', name: 'Belapur', city: 'Belapur', state: 'Maharashtra', postalCode: '400614', lat: 19.0224, lng: 73.0367, description: 'Premium escorts in Belapur, CBD Belapur available 24/7.', reviewCount: 67, areas: ['CBD Belapur', 'Belapur Sector 11', 'Belapur Village'] },
  { slug: 'bhandup', name: 'Bhandup', city: 'Bhandup', state: 'Maharashtra', postalCode: '400078', lat: 19.1509, lng: 72.9406, description: 'Premium escorts in Bhandup available 24/7.', reviewCount: 58, areas: ['Bhandup West', 'Bhandup East', 'Nahur', 'Kanjurmarg'] },
  { slug: 'bhayandar', name: 'Bhayandar', city: 'Bhayandar', state: 'Maharashtra', postalCode: '401101', lat: 19.3003, lng: 72.8503, description: 'Premium escorts in Bhayandar available 24/7.', reviewCount: 62, areas: ['Bhayandar East', 'Bhayandar West', 'Navghar'] },
  { slug: 'bhiwandi', name: 'Bhiwandi', city: 'Bhiwandi', state: 'Maharashtra', postalCode: '421302', lat: 19.2968, lng: 73.0625, description: 'Premium escorts in Bhiwandi available 24/7.', reviewCount: 54, areas: ['Bhiwandi City', 'Purna', 'Anjurphata'] },
  { slug: 'bhopal', name: 'Bhopal', city: 'Bhopal', state: 'Madhya Pradesh', postalCode: '462001', lat: 23.2599, lng: 77.4126, description: 'Premium escorts in Bhopal available 24/7.', reviewCount: 98, areas: ['MP Nagar', 'Arera Colony', 'New Market', 'Shivaji Nagar'] },
  { slug: 'bhubaneswar', name: 'Bhubaneswar', city: 'Bhubaneswar', state: 'Odisha', postalCode: '751001', lat: 20.2961, lng: 85.8245, description: 'Premium escorts in Bhubaneswar available 24/7.', reviewCount: 76, areas: ['Saheed Nagar', 'Patia', 'Nayapalli', 'Chandrasekharpur'] },
  { slug: 'boisar', name: 'Boisar', city: 'Boisar', state: 'Maharashtra', postalCode: '401501', lat: 19.8135, lng: 72.7616, description: 'Premium escorts in Boisar available 24/7.', reviewCount: 34, areas: ['Boisar Station', 'TAPS Colony', 'Tarapur'] },
  { slug: 'borivali', name: 'Borivali', city: 'Borivali', state: 'Maharashtra', postalCode: '400066', lat: 19.2307, lng: 72.8567, description: 'Premium escorts in Borivali available 24/7.', reviewCount: 123, areas: ['Borivali West', 'Borivali East', 'Dahisar', 'Kandivali'] },
  { slug: 'byculla', name: 'Byculla', city: 'Byculla', state: 'Maharashtra', postalCode: '400027', lat: 18.9714, lng: 72.8393, description: 'Premium escorts in Byculla available 24/7.', reviewCount: 72, areas: ['Byculla East', 'Byculla West', 'Mazgaon', 'Nagpada'] },
  { slug: 'chandigarh', name: 'Chandigarh', city: 'Chandigarh', state: 'Punjab', postalCode: '160001', lat: 30.7333, lng: 76.7794, description: 'Premium escorts in Chandigarh available 24/7.', reviewCount: 145, areas: ['Sector 17', 'Sector 22', 'Sector 35', 'Mohali', 'Panchkula'] },
  { slug: 'charni-road', name: 'Charni Road', city: 'Charni Road', state: 'Maharashtra', postalCode: '400004', lat: 18.9547, lng: 72.8153, description: 'Premium escorts in Charni Road area available 24/7.', reviewCount: 53, areas: ['Charni Road Station', 'Opera House', 'Grant Road'] },
  { slug: 'chembur', name: 'Chembur', city: 'Chembur', state: 'Maharashtra', postalCode: '400071', lat: 19.0627, lng: 72.8998, description: 'Premium escorts in Chembur available 24/7.', reviewCount: 89, areas: ['Chembur East', 'Chembur West', 'Govandi', 'Mankhurd'] },
  { slug: 'chennai', name: 'Chennai', city: 'Chennai', state: 'Tamil Nadu', postalCode: '600001', lat: 13.0827, lng: 80.2707, description: 'Premium escorts in Chennai available 24/7.', reviewCount: 287, areas: ['Anna Nagar', 'T. Nagar', 'Adyar', 'Nungambakkam', 'OMR', 'Velachery'] },
  { slug: 'chinchpokli', name: 'Chinchpokli', city: 'Chinchpokli', state: 'Maharashtra', postalCode: '400012', lat: 18.9899, lng: 72.8448, description: 'Premium escorts in Chinchpokli available 24/7.', reviewCount: 41, areas: ['Chinchpokli Station', 'Cotton Green', 'Sewree'] },
  { slug: 'churchgate', name: 'Churchgate', city: 'Churchgate', state: 'Maharashtra', postalCode: '400020', lat: 18.9322, lng: 72.8264, description: 'Premium escorts in Churchgate, South Mumbai available 24/7.', reviewCount: 97, areas: ['Churchgate', 'Marine Lines', 'Nariman Point', 'Fort'] },
  { slug: 'coimbatore', name: 'Coimbatore', city: 'Coimbatore', state: 'Tamil Nadu', postalCode: '641001', lat: 11.0168, lng: 76.9558, description: 'Premium escorts in Coimbatore available 24/7.', reviewCount: 112, areas: ['RS Puram', 'Gandhipuram', 'Peelamedu', 'Saibaba Colony'] },
  { slug: 'colaba', name: 'Colaba', city: 'Colaba', state: 'Maharashtra', postalCode: '400005', lat: 18.9067, lng: 72.8147, description: 'Premium escorts in Colaba, South Mumbai available 24/7.', reviewCount: 132, areas: ['Colaba Causeway', 'Gateway of India', 'Regal Cinema', 'Electric House'] },
  { slug: 'cst', name: 'CST', city: 'CST', state: 'Maharashtra', postalCode: '400001', lat: 18.9398, lng: 72.8354, description: 'Premium escorts near CST, South Mumbai available 24/7.', reviewCount: 78, areas: ['CST Area', 'Fort', 'VT', 'Ballard Estate'] },
  { slug: 'dadar', name: 'Dadar', city: 'Dadar', state: 'Maharashtra', postalCode: '400014', lat: 19.0178, lng: 72.8478, description: 'Premium escorts in Dadar, Central Mumbai available 24/7.', reviewCount: 108, areas: ['Dadar West', 'Dadar East', 'Shivaji Park', 'Prabhadevi'] },
  { slug: 'dehradun', name: 'Dehradun', city: 'Dehradun', state: 'Uttarakhand', postalCode: '248001', lat: 30.3165, lng: 78.0322, description: 'Premium escorts in Dehradun available 24/7.', reviewCount: 89, areas: ['Rajpur Road', 'Paltan Bazaar', 'Clement Town', 'Prem Nagar'] },
  { slug: 'delhi', name: 'Delhi', city: 'Delhi', state: 'Delhi', postalCode: '110001', lat: 28.6139, lng: 77.2090, description: 'Premium escorts in Delhi available 24/7.', reviewCount: 456, areas: ['Connaught Place', 'Lajpat Nagar', 'South Extension', 'Karol Bagh', 'Hauz Khas', 'DLF'] },
  { slug: 'diva', name: 'Diva', city: 'Diva', state: 'Maharashtra', postalCode: '400612', lat: 19.2000, lng: 73.0500, description: 'Premium escorts in Diva available 24/7.', reviewCount: 36, areas: ['Diva Station', 'Mumbra Bypass Area'] },
  { slug: 'dombivli', name: 'Dombivli', city: 'Dombivli', state: 'Maharashtra', postalCode: '421201', lat: 19.2167, lng: 73.0833, description: 'Premium escorts in Dombivli available 24/7.', reviewCount: 84, areas: ['Dombivli East', 'Dombivli West', 'Manpada', 'Thakurli'] },
  { slug: 'fort', name: 'Fort', city: 'Fort', state: 'Maharashtra', postalCode: '400001', lat: 18.9346, lng: 72.8358, description: 'Premium escorts in Fort, South Mumbai available 24/7.', reviewCount: 91, areas: ['Fort Area', 'Kala Ghoda', 'Horniman Circle', 'Fountain'] },
  { slug: 'ghansoli', name: 'Ghansoli', city: 'Ghansoli', state: 'Maharashtra', postalCode: '400701', lat: 19.1167, lng: 72.9833, description: 'Premium escorts in Ghansoli, Navi Mumbai available 24/7.', reviewCount: 48, areas: ['Ghansoli Sector', 'Airoli Road', 'Parsik Hill'] },
  { slug: 'ghatkopar', name: 'Ghatkopar', city: 'Ghatkopar', state: 'Maharashtra', postalCode: '400077', lat: 19.0856, lng: 72.9081, description: 'Premium escorts in Ghatkopar available 24/7.', reviewCount: 117, areas: ['Ghatkopar East', 'Ghatkopar West', 'Vikhroli', 'Kurla'] },
  { slug: 'goa', name: 'Goa', city: 'Goa', state: 'Goa', postalCode: '403001', lat: 15.4989, lng: 73.8278, description: 'Premium escorts in Goa available 24/7.', reviewCount: 231, areas: ['Panaji', 'Calangute', 'Baga', 'Anjuna', 'Vasco da Gama', 'Margao'] },
  { slug: 'goregaon', name: 'Goregaon', city: 'Goregaon', state: 'Maharashtra', postalCode: '400063', lat: 19.1663, lng: 72.8526, description: 'Premium escorts in Goregaon available 24/7.', reviewCount: 102, areas: ['Goregaon East', 'Goregaon West', 'Film City', 'Aarey Colony'] },
  { slug: 'govandi', name: 'Govandi', city: 'Govandi', state: 'Maharashtra', postalCode: '400043', lat: 19.0526, lng: 72.9108, description: 'Premium escorts in Govandi available 24/7.', reviewCount: 53, areas: ['Govandi Station', 'Deonar', 'Trombay'] },
  { slug: 'grant-road', name: 'Grant Road', city: 'Grant Road', state: 'Maharashtra', postalCode: '400007', lat: 18.9636, lng: 72.8188, description: 'Premium escorts in Grant Road area available 24/7.', reviewCount: 74, areas: ['Grant Road East', 'Grant Road West', 'Tardeo', 'Nana Chowk'] },
  { slug: 'gurgaon', name: 'Gurgaon', city: 'Gurgaon', state: 'Haryana', postalCode: '122001', lat: 28.4595, lng: 77.0266, description: 'Premium escorts in Gurgaon available 24/7.', reviewCount: 267, areas: ['DLF Phase 1-5', 'Cyber City', 'Sohna Road', 'Golf Course Road', 'MG Road'] },
  { slug: 'guwahati', name: 'Guwahati', city: 'Guwahati', state: 'Assam', postalCode: '781001', lat: 26.1445, lng: 91.7362, description: 'Premium escorts in Guwahati available 24/7.', reviewCount: 94, areas: ['Dispur', 'Sixmile', 'Lastgate', 'Paltan Bazaar'] },
  { slug: 'gwalior', name: 'Gwalior', city: 'Gwalior', state: 'Madhya Pradesh', postalCode: '474001', lat: 26.2183, lng: 78.1828, description: 'Premium escorts in Gwalior available 24/7.', reviewCount: 67, areas: ['Lashkar', 'City Centre', 'Thatipur', 'Morar'] },
  { slug: 'hyderabad', name: 'Hyderabad', city: 'Hyderabad', state: 'Telangana', postalCode: '500001', lat: 17.3850, lng: 78.4867, description: 'Premium escorts in Hyderabad available 24/7.', reviewCount: 342, areas: ['Banjara Hills', 'Jubilee Hills', 'Hitech City', 'Gachibowli', 'Madhapur', 'Kondapur'] },
  { slug: 'indore', name: 'Indore', city: 'Indore', state: 'Madhya Pradesh', postalCode: '452001', lat: 22.7196, lng: 75.8577, description: 'Premium escorts in Indore available 24/7.', reviewCount: 121, areas: ['Vijay Nagar', 'AB Road', 'Palasia', 'New Palasia', 'LIG Square'] },
  { slug: 'jaipur', name: 'Jaipur', city: 'Jaipur', state: 'Rajasthan', postalCode: '302001', lat: 26.9124, lng: 75.7873, description: 'Premium escorts in Jaipur, Pink City available 24/7.', reviewCount: 178, areas: ['MI Road', 'Vaishali Nagar', 'Malviya Nagar', 'C-Scheme', 'Mansarovar'] },
  { slug: 'jalandhar', name: 'Jalandhar', city: 'Jalandhar', state: 'Punjab', postalCode: '144001', lat: 31.3260, lng: 75.5762, description: 'Premium escorts in Jalandhar available 24/7.', reviewCount: 87, areas: ['Model Town', 'Civil Lines', 'Lajpat Nagar', 'Guru Nanak Nagar'] },
  { slug: 'jodhpur', name: 'Jodhpur', city: 'Jodhpur', state: 'Rajasthan', postalCode: '342001', lat: 26.2389, lng: 73.0243, description: 'Premium escorts in Jodhpur, Blue City available 24/7.', reviewCount: 73, areas: ['Sardarpura', 'Paota', 'Shastri Nagar', 'Residency Road'] },
  { slug: 'jogeshwari', name: 'Jogeshwari', city: 'Jogeshwari', state: 'Maharashtra', postalCode: '400102', lat: 19.1366, lng: 72.8476, description: 'Premium escorts in Jogeshwari available 24/7.', reviewCount: 78, areas: ['Jogeshwari East', 'Jogeshwari West', 'Andheri Link Road', 'DN Nagar'] },
  { slug: 'juhu', name: 'Juhu', city: 'Juhu', state: 'Maharashtra', postalCode: '400049', lat: 19.1075, lng: 72.8263, description: 'Premium escorts in Juhu available 24/7. Near Juhu Beach.', reviewCount: 167, areas: ['Juhu Beach', 'JVPD Scheme', 'Vile Parle West', 'Navpada'] },
  { slug: 'juinagar', name: 'Juinagar', city: 'Juinagar', state: 'Maharashtra', postalCode: '400706', lat: 19.0326, lng: 73.0224, description: 'Premium escorts in Juinagar, Navi Mumbai available 24/7.', reviewCount: 44, areas: ['Juinagar Sector 1', 'Juinagar Sector 3', 'Sanpada'] },
  { slug: 'kalamboli', name: 'Kalamboli', city: 'Kalamboli', state: 'Maharashtra', postalCode: '410218', lat: 19.2241, lng: 73.1263, description: 'Premium escorts in Kalamboli, Navi Mumbai available 24/7.', reviewCount: 38, areas: ['Kalamboli Sector 1', 'Kalamboli Central Market', 'Kharghar Link Road'] },
  { slug: 'kalwa', name: 'Kalwa', city: 'Kalwa', state: 'Maharashtra', postalCode: '400605', lat: 19.1751, lng: 73.0227, description: 'Premium escorts in Kalwa, Thane available 24/7.', reviewCount: 32, areas: ['Kalwa Station', 'Mumbra Road', 'Vitawa'] },
  { slug: 'kalyan', name: 'Kalyan', city: 'Kalyan', state: 'Maharashtra', postalCode: '421301', lat: 19.2350, lng: 73.1290, description: 'Premium escorts in Kalyan available 24/7.', reviewCount: 109, areas: ['Kalyan East', 'Kalyan West', 'Shahad', 'Ambivali'] },
  { slug: 'kamothe', name: 'Kamothe', city: 'Kamothe', state: 'Maharashtra', postalCode: '410209', lat: 19.0120, lng: 73.0860, description: 'Premium escorts in Kamothe, Navi Mumbai available 24/7.', reviewCount: 51, areas: ['Kamothe Sector 1', 'Kamothe Sector 6', 'Mansarovar Complex'] },
  { slug: 'kandivali', name: 'Kandivali', city: 'Kandivali', state: 'Maharashtra', postalCode: '400067', lat: 19.2095, lng: 72.8460, description: 'Premium escorts in Kandivali available 24/7.', reviewCount: 118, areas: ['Kandivali East', 'Kandivali West', 'Charkop', 'Lokhandwala Kandivali'] },
  { slug: 'kanjurmarg', name: 'Kanjurmarg', city: 'Kanjurmarg', state: 'Maharashtra', postalCode: '400042', lat: 19.1265, lng: 72.9371, description: 'Premium escorts in Kanjurmarg available 24/7.', reviewCount: 62, areas: ['Kanjurmarg East', 'Kanjurmarg West', 'Bhandup Complex'] },
  { slug: 'kanpur', name: 'Kanpur', city: 'Kanpur', state: 'Uttar Pradesh', postalCode: '208001', lat: 26.4499, lng: 80.3319, description: 'Premium escorts in Kanpur available 24/7.', reviewCount: 134, areas: ['Civil Lines', 'Swaroop Nagar', 'Harsh Nagar', 'Kidwai Nagar'] },
  { slug: 'karjat', name: 'Karjat', city: 'Karjat', state: 'Maharashtra', postalCode: '410201', lat: 18.9167, lng: 73.3167, description: 'Premium escorts in Karjat available 24/7.', reviewCount: 27, areas: ['Karjat Station', 'Khopoli Road', 'Palasdhari'] },
  { slug: 'kasara', name: 'Kasara', city: 'Kasara', state: 'Maharashtra', postalCode: '422402', lat: 19.8167, lng: 73.4667, description: 'Premium escorts in Kasara available 24/7.', reviewCount: 22, areas: ['Kasara Station', 'Igatpuri Road'] },
  { slug: 'khar', name: 'Khar', city: 'Khar', state: 'Maharashtra', postalCode: '400052', lat: 19.0722, lng: 72.8344, description: 'Premium escorts in Khar, Mumbai available 24/7.', reviewCount: 93, areas: ['Khar West', 'Khar East', 'Khar Danda', 'SV Road Khar'] },
  { slug: 'khar-road', name: 'Khar Road', city: 'Khar Road', state: 'Maharashtra', postalCode: '400052', lat: 19.0746, lng: 72.8334, description: 'Premium escorts near Khar Road available 24/7.', reviewCount: 76, areas: ['Khar Road Station', 'Linking Road', 'Waterfield Road'] },
  { slug: 'kharghar', name: 'Kharghar', city: 'Kharghar', state: 'Maharashtra', postalCode: '410210', lat: 19.0476, lng: 73.0741, description: 'Premium escorts in Kharghar, Navi Mumbai available 24/7.', reviewCount: 88, areas: ['Kharghar Sector 1-35', 'Central Park', 'Kharghar Hills'] },
  { slug: 'khopoli', name: 'Khopoli', city: 'Khopoli', state: 'Maharashtra', postalCode: '410203', lat: 18.7833, lng: 73.3333, description: 'Premium escorts in Khopoli available 24/7.', reviewCount: 29, areas: ['Khopoli Station', 'MIDC Area', 'Rasayani'] },
  { slug: 'kochi', name: 'Kochi', city: 'Kochi', state: 'Kerala', postalCode: '682001', lat: 9.9312, lng: 76.2673, description: 'Premium escorts in Kochi available 24/7.', reviewCount: 143, areas: ['Ernakulam', 'Marine Drive', 'MG Road', 'Kakkanad', 'Edapally'] },
  { slug: 'kolkata', name: 'Kolkata', city: 'Kolkata', state: 'West Bengal', postalCode: '700001', lat: 22.5726, lng: 88.3639, description: 'Premium escorts in Kolkata available 24/7.', reviewCount: 278, areas: ['Park Street', 'Salt Lake', 'New Town', 'Ballygunge', 'Howrah'] },
  { slug: 'kopar-khairane', name: 'Kopar Khairane', city: 'Kopar Khairane', state: 'Maharashtra', postalCode: '400709', lat: 19.1017, lng: 73.0098, description: 'Premium escorts in Kopar Khairane, Navi Mumbai available 24/7.', reviewCount: 55, areas: ['Kopar Khairane Sector 1', 'Sector 7', 'Ghansoli Road'] },
  { slug: 'kurla', name: 'Kurla', city: 'Kurla', state: 'Maharashtra', postalCode: '400070', lat: 19.0736, lng: 72.8797, description: 'Premium escorts in Kurla available 24/7.', reviewCount: 96, areas: ['Kurla West', 'Kurla East', 'Chunabhatti', 'Ghatla'] },
  { slug: 'lokhandwala', name: 'Lokhandwala', city: 'Lokhandwala', state: 'Maharashtra', postalCode: '400053', lat: 19.1337, lng: 72.8283, description: 'Premium escorts in Lokhandwala, Andheri available 24/7.', reviewCount: 142, areas: ['Lokhandwala Complex', 'Oshiwara', 'Link Road', 'Four Bungalows'] },
  { slug: 'lower-parel', name: 'Lower Parel', city: 'Lower Parel', state: 'Maharashtra', postalCode: '400013', lat: 19.0000, lng: 72.8330, description: 'Premium escorts in Lower Parel available 24/7.', reviewCount: 127, areas: ['Lower Parel', 'Parel', 'Worli', 'Elphinstone Road'] },
  { slug: 'lucknow', name: 'Lucknow', city: 'Lucknow', state: 'Uttar Pradesh', postalCode: '226001', lat: 26.8467, lng: 80.9462, description: 'Premium escorts in Lucknow available 24/7.', reviewCount: 189, areas: ['Hazratganj', 'Gomti Nagar', 'Mahanagar', 'Alambagh', 'Indira Nagar'] },
  { slug: 'ludhiana', name: 'Ludhiana', city: 'Ludhiana', state: 'Punjab', postalCode: '141001', lat: 30.9010, lng: 75.8573, description: 'Premium escorts in Ludhiana available 24/7.', reviewCount: 112, areas: ['Model Town', 'BRS Nagar', 'Sarabha Nagar', 'Civil Lines'] },
  { slug: 'mahalaxmi', name: 'Mahalaxmi', city: 'Mahalaxmi', state: 'Maharashtra', postalCode: '400034', lat: 18.9819, lng: 72.8230, description: 'Premium escorts in Mahalaxmi, Mumbai available 24/7.', reviewCount: 70, areas: ['Mahalaxmi Station', 'Race Course', 'Jacob Circle', 'Worli Naka'] },
  { slug: 'mahim', name: 'Mahim', city: 'Mahim', state: 'Maharashtra', postalCode: '400016', lat: 19.0386, lng: 72.8410, description: 'Premium escorts in Mahim, Mumbai available 24/7.', reviewCount: 82, areas: ['Mahim West', 'Mahim East', 'Dharavi', 'Sion'] },
  { slug: 'malad', name: 'Malad', city: 'Malad', state: 'Maharashtra', postalCode: '400064', lat: 19.1860, lng: 72.8481, description: 'Premium escorts in Malad available 24/7.', reviewCount: 131, areas: ['Malad East', 'Malad West', 'Malvani', 'Orlem', 'Mindspace'] },
  { slug: 'mangalore', name: 'Mangalore', city: 'Mangalore', state: 'Karnataka', postalCode: '575001', lat: 12.9141, lng: 74.8560, description: 'Premium escorts in Mangalore available 24/7.', reviewCount: 89, areas: ['Hampankatta', 'Kadri', 'Pandeshwar', 'Falnir'] },
  { slug: 'mankhurd', name: 'Mankhurd', city: 'Mankhurd', state: 'Maharashtra', postalCode: '400043', lat: 19.0399, lng: 72.9253, description: 'Premium escorts in Mankhurd available 24/7.', reviewCount: 48, areas: ['Mankhurd Station', 'Vashi Naka', 'Shivaji Nagar'] },
  { slug: 'marine-lines', name: 'Marine Lines', city: 'Marine Lines', state: 'Maharashtra', postalCode: '400020', lat: 18.9424, lng: 72.8229, description: 'Premium escorts in Marine Lines available 24/7.', reviewCount: 91, areas: ['Marine Lines Station', 'Marine Drive', 'Churchgate', 'Charni Road'] },
  { slug: 'masjid-bandar', name: 'Masjid Bandar', city: 'Masjid Bandar', state: 'Maharashtra', postalCode: '400009', lat: 18.9466, lng: 72.8355, description: 'Premium escorts in Masjid Bandar available 24/7.', reviewCount: 46, areas: ['Masjid Station', 'Ghee Board Lane', 'Khoja Alley'] },
  { slug: 'matunga', name: 'Matunga', city: 'Matunga', state: 'Maharashtra', postalCode: '400019', lat: 19.0237, lng: 72.8533, description: 'Premium escorts in Matunga available 24/7.', reviewCount: 65, areas: ['Matunga West', 'Matunga East', 'Kings Circle', 'Dharavi'] },
  { slug: 'mira-road', name: 'Mira Road', city: 'Mira Road', state: 'Maharashtra', postalCode: '401107', lat: 19.2830, lng: 72.8696, description: 'Premium escorts in Mira Road available 24/7.', reviewCount: 97, areas: ['Mira Road East', 'Mira Road West', 'Bhayander Link Road', 'Silver Park'] },
  { slug: 'mulund', name: 'Mulund', city: 'Mulund', state: 'Maharashtra', postalCode: '400080', lat: 19.1769, lng: 72.9544, description: 'Premium escorts in Mulund available 24/7.', reviewCount: 103, areas: ['Mulund East', 'Mulund West', 'Nahur', 'Bhandup'] },
  { slug: 'mumbai-airport', name: 'Mumbai Airport', city: 'Mumbai Airport', state: 'Maharashtra', postalCode: '400099', lat: 19.0896, lng: 72.8656, description: 'Premium escorts near Mumbai Airport available 24/7.', reviewCount: 176, areas: ['Andheri Airport Zone', 'BAIF Road', 'Sahar', 'International Departures Area'] },
  { slug: 'mumbai-central', name: 'Mumbai Central', city: 'Mumbai Central', state: 'Maharashtra', postalCode: '400008', lat: 18.9696, lng: 72.8194, description: 'Premium escorts in Mumbai Central available 24/7.', reviewCount: 115, areas: ['Mumbai Central Station', 'Tardeo', 'Currey Road', 'Bhendi Bazaar'] },
  { slug: 'mumbra', name: 'Mumbra', city: 'Mumbra', state: 'Maharashtra', postalCode: '400612', lat: 19.1820, lng: 73.0213, description: 'Premium escorts in Mumbra available 24/7.', reviewCount: 54, areas: ['Mumbra Station', 'Shil Phata', 'Diva Junction'] },
  { slug: 'mysore', name: 'Mysore', city: 'Mysore', state: 'Karnataka', postalCode: '570001', lat: 12.2958, lng: 76.6394, description: 'Premium escorts in Mysore available 24/7.', reviewCount: 98, areas: ['Nazarbad', 'Saraswathipuram', 'Jayalakshmipuram', 'Vijayanagar'] },
  { slug: 'nagpur', name: 'Nagpur', city: 'Nagpur', state: 'Maharashtra', postalCode: '440001', lat: 21.1458, lng: 79.0882, description: 'Premium escorts in Nagpur available 24/7.', reviewCount: 147, areas: ['Dharampeth', 'Sitabuldi', 'Bajaj Nagar', 'Laxmi Nagar', 'Sadar'] },
  { slug: 'nahur', name: 'Nahur', city: 'Nahur', state: 'Maharashtra', postalCode: '400078', lat: 19.1487, lng: 72.9390, description: 'Premium escorts in Nahur available 24/7.', reviewCount: 42, areas: ['Nahur Station', 'Mulund Link Road', 'Bhandup Complex'] },
  { slug: 'naigaon', name: 'Naigaon', city: 'Naigaon', state: 'Maharashtra', postalCode: '401208', lat: 19.3600, lng: 72.8600, description: 'Premium escorts in Naigaon available 24/7.', reviewCount: 46, areas: ['Naigaon East', 'Naigaon West', 'Pelhar'] },
  { slug: 'nalasopara', name: 'Nalasopara', city: 'Nalasopara', state: 'Maharashtra', postalCode: '401209', lat: 19.4156, lng: 72.7957, description: 'Premium escorts in Nalasopara available 24/7.', reviewCount: 68, areas: ['Nalasopara East', 'Nalasopara West', 'Achole Road'] },
  { slug: 'nariman-point', name: 'Nariman Point', city: 'Nariman Point', state: 'Maharashtra', postalCode: '400021', lat: 18.9255, lng: 72.8242, description: 'Premium escorts in Nariman Point, South Mumbai available 24/7.', reviewCount: 112, areas: ['Nariman Point', 'Marine Drive', 'Backbay Reclamation', 'Cuffe Parade'] },
  { slug: 'nashik', name: 'Nashik', city: 'Nashik', state: 'Maharashtra', postalCode: '422001', lat: 19.9975, lng: 73.7898, description: 'Premium escorts in Nashik available 24/7.', reviewCount: 134, areas: ['College Road', 'Gangapur Road', 'Pathardi Phata', 'Cidco'] },
  { slug: 'navi-mumbai', name: 'Navi Mumbai', city: 'Navi Mumbai', state: 'Maharashtra', postalCode: '400703', lat: 19.0330, lng: 73.0297, description: 'Premium escorts in Navi Mumbai available 24/7.', reviewCount: 198, areas: ['Vashi', 'Belapur', 'Kharghar', 'Panvel', 'Airoli', 'Nerul'] },
  { slug: 'neral', name: 'Neral', city: 'Neral', state: 'Maharashtra', postalCode: '410101', lat: 18.8647, lng: 73.2749, description: 'Premium escorts in Neral available 24/7.', reviewCount: 24, areas: ['Neral Station', 'Matheran Road', 'Karjat Road'] },
  { slug: 'nerul', name: 'Nerul', city: 'Nerul', state: 'Maharashtra', postalCode: '400706', lat: 19.0330, lng: 73.0181, description: 'Premium escorts in Nerul, Navi Mumbai available 24/7.', reviewCount: 76, areas: ['Nerul Sector 1', 'Nerul Sector 23', 'Sanpada', 'Seawoods'] },
  { slug: 'noida', name: 'Noida', city: 'Noida', state: 'Uttar Pradesh', postalCode: '201301', lat: 28.5355, lng: 77.3910, description: 'Premium escorts in Noida available 24/7.', reviewCount: 234, areas: ['Sector 18', 'Sector 62', 'Sector 15', 'Sector 25', 'Greater Noida'] },
  { slug: 'palghar', name: 'Palghar', city: 'Palghar', state: 'Maharashtra', postalCode: '401404', lat: 19.6967, lng: 72.7659, description: 'Premium escorts in Palghar available 24/7.', reviewCount: 41, areas: ['Palghar Station', 'Saphale Road', 'Manor Road'] },
  { slug: 'panvel', name: 'Panvel', city: 'Panvel', state: 'Maharashtra', postalCode: '410206', lat: 18.9894, lng: 73.1175, description: 'Premium escorts in Panvel available 24/7.', reviewCount: 94, areas: ['Panvel Station', 'Old Panvel', 'New Panvel', 'Kalamboli'] },
  { slug: 'parel', name: 'Parel', city: 'Parel', state: 'Maharashtra', postalCode: '400012', lat: 19.0024, lng: 72.8444, description: 'Premium escorts in Parel available 24/7.', reviewCount: 108, areas: ['Parel East', 'Parel West', 'Lalbaug', 'Lower Parel'] },
  { slug: 'patna', name: 'Patna', city: 'Patna', state: 'Bihar', postalCode: '800001', lat: 25.5941, lng: 85.1376, description: 'Premium escorts in Patna available 24/7.', reviewCount: 123, areas: ['Fraser Road', 'Boring Road', 'Kankarbagh', 'Rajendra Nagar'] },
  { slug: 'powai', name: 'Powai', city: 'Powai', state: 'Maharashtra', postalCode: '400076', lat: 19.1176, lng: 72.9060, description: 'Premium escorts in Powai available 24/7. Near IIT and Hiranandani.', reviewCount: 152, areas: ['Hiranandani Gardens', 'IIT Powai', 'Powai Lake', 'Chandivali'] },
  { slug: 'prabhadevi', name: 'Prabhadevi', city: 'Prabhadevi', state: 'Maharashtra', postalCode: '400025', lat: 19.0148, lng: 72.8328, description: 'Premium escorts in Prabhadevi available 24/7.', reviewCount: 79, areas: ['Prabhadevi', 'Worli Naka', 'Century Bazaar', 'Mahim Causeway'] },
  { slug: 'pune', name: 'Pune', city: 'Pune', state: 'Maharashtra', postalCode: '411001', lat: 18.5204, lng: 73.8567, description: 'Premium escorts in Pune available 24/7.', reviewCount: 312, areas: ['Koregaon Park', 'Baner', 'Wakad', 'Hinjewadi', 'Kothrud', 'Aundh'] },
  { slug: 'rabale', name: 'Rabale', city: 'Rabale', state: 'Maharashtra', postalCode: '400701', lat: 19.1029, lng: 72.9975, description: 'Premium escorts in Rabale, Navi Mumbai available 24/7.', reviewCount: 39, areas: ['Rabale MIDC', 'Airoli Road', 'TTC Area'] },
  { slug: 'rajkot', name: 'Rajkot', city: 'Rajkot', state: 'Gujarat', postalCode: '360001', lat: 22.3039, lng: 70.8022, description: 'Premium escorts in Rajkot available 24/7.', reviewCount: 96, areas: ['Race Course', 'Kalawad Road', 'University Road', '150 Feet Ring Road'] },
  { slug: 'ranchi', name: 'Ranchi', city: 'Ranchi', state: 'Jharkhand', postalCode: '834001', lat: 23.3441, lng: 85.3096, description: 'Premium escorts in Ranchi available 24/7.', reviewCount: 87, areas: ['Main Road', 'Harmu', 'Bariatu', 'Kadru'] },
  { slug: 'sakinaka', name: 'Sakinaka', city: 'Sakinaka', state: 'Maharashtra', postalCode: '400072', lat: 19.0978, lng: 72.8893, description: 'Premium escorts in Sakinaka available 24/7.', reviewCount: 74, areas: ['Sakinaka Junction', 'Powai Road', 'Chandivali'] },
  { slug: 'sanpada', name: 'Sanpada', city: 'Sanpada', state: 'Maharashtra', postalCode: '400705', lat: 19.0509, lng: 73.0141, description: 'Premium escorts in Sanpada, Navi Mumbai available 24/7.', reviewCount: 52, areas: ['Sanpada Sector 1', 'Juinagar Road', 'Vashi Link Road'] },
  { slug: 'santacruz', name: 'Santacruz', city: 'Santacruz', state: 'Maharashtra', postalCode: '400055', lat: 19.0822, lng: 72.8419, description: 'Premium escorts in Santacruz available 24/7.', reviewCount: 93, areas: ['Santacruz West', 'Santacruz East', 'Vakola', 'Khar Road'] },
  { slug: 'saphale', name: 'Saphale', city: 'Saphale', state: 'Maharashtra', postalCode: '401405', lat: 19.7131, lng: 72.9547, description: 'Premium escorts in Saphale available 24/7.', reviewCount: 26, areas: ['Saphale Station', 'Agloli'] },
  { slug: 'seawood', name: 'Seawood', city: 'Seawood', state: 'Maharashtra', postalCode: '400706', lat: 19.0207, lng: 73.0248, description: 'Premium escorts in Seawood, Navi Mumbai available 24/7.', reviewCount: 58, areas: ['Seawoods Estate', 'Nerul Sector 40', 'DLF Seawoods'] },
  { slug: 'siliguri', name: 'Siliguri', city: 'Siliguri', state: 'West Bengal', postalCode: '734001', lat: 26.7271, lng: 88.3952, description: 'Premium escorts in Siliguri available 24/7.', reviewCount: 76, areas: ['Pradhan Nagar', 'Sevoke Road', 'Bagdogra', 'Jalpaiguri Road'] },
  { slug: 'sion', name: 'Sion', city: 'Sion', state: 'Maharashtra', postalCode: '400022', lat: 19.0394, lng: 72.8622, description: 'Premium escorts in Sion available 24/7.', reviewCount: 67, areas: ['Sion Hospital Area', 'Dharavi', 'Chunabhatti', 'Antop Hill'] },
  { slug: 'surat', name: 'Surat', city: 'Surat', state: 'Gujarat', postalCode: '395001', lat: 21.1702, lng: 72.8311, description: 'Premium escorts in Surat available 24/7.', reviewCount: 165, areas: ['Adajan', 'Vesu', 'Katargam', 'Varachha', 'Ring Road'] },
  { slug: 'thakurli', name: 'Thakurli', city: 'Thakurli', state: 'Maharashtra', postalCode: '421201', lat: 19.2230, lng: 73.0780, description: 'Premium escorts in Thakurli available 24/7.', reviewCount: 38, areas: ['Thakurli Station', 'Dombivli Road', 'Kalyan Road'] },
  { slug: 'thane', name: 'Thane', city: 'Thane', state: 'Maharashtra', postalCode: '400601', lat: 19.2183, lng: 72.9781, description: 'Premium escorts in Thane available 24/7.', reviewCount: 187, areas: ['Thane West', 'Thane East', 'Ghodbunder Road', 'Hiranandani Estate', 'Kopri'] },
  { slug: 'titwala', name: 'Titwala', city: 'Titwala', state: 'Maharashtra', postalCode: '421605', lat: 19.3028, lng: 73.2039, description: 'Premium escorts in Titwala available 24/7.', reviewCount: 31, areas: ['Titwala Station', 'Khardi Road', 'Kelavli'] },
  { slug: 'udaipur', name: 'Udaipur', city: 'Udaipur', state: 'Rajasthan', postalCode: '313001', lat: 24.5854, lng: 73.7125, description: 'Premium escorts in Udaipur, Lake City available 24/7.', reviewCount: 94, areas: ['Fateh Sagar', 'Sukhadia Circle', 'Sector 4', 'Chetak Circle'] },
  { slug: 'ulhasnagar', name: 'Ulhasnagar', city: 'Ulhasnagar', state: 'Maharashtra', postalCode: '421003', lat: 19.2186, lng: 73.1629, description: 'Premium escorts in Ulhasnagar available 24/7.', reviewCount: 67, areas: ['Camp 1', 'Camp 3', 'Camp 4', 'Camp 5', 'Ambernath Road'] },
  { slug: 'ulwe', name: 'Ulwe', city: 'Ulwe', state: 'Maharashtra', postalCode: '410206', lat: 18.9817, lng: 73.0384, description: 'Premium escorts in Ulwe, Navi Mumbai available 24/7.', reviewCount: 43, areas: ['Ulwe Sector 1', 'Sector 8', 'CIDCO Housing', 'Kalamboli Highway'] },
  { slug: 'varanasi', name: 'Varanasi', city: 'Varanasi', state: 'Uttar Pradesh', postalCode: '221001', lat: 25.3176, lng: 82.9739, description: 'Premium escorts in Varanasi available 24/7.', reviewCount: 112, areas: ['Assi', 'Sigra', 'Lanka', 'Nadesar', 'Cantonment'] },
  { slug: 'vasai', name: 'Vasai', city: 'Vasai', state: 'Maharashtra', postalCode: '401202', lat: 19.3677, lng: 72.8098, description: 'Premium escorts in Vasai available 24/7.', reviewCount: 78, areas: ['Vasai East', 'Vasai West', 'Virar Road', 'Bassein Road'] },
  { slug: 'vashi', name: 'Vashi', city: 'Vashi', state: 'Maharashtra', postalCode: '400703', lat: 19.0759, lng: 73.0073, description: 'Premium escorts in Vashi, Navi Mumbai available 24/7.', reviewCount: 132, areas: ['Vashi Sector 1-30', 'Vashi Plaza', 'Wonder Mall', 'APMC'] },
  { slug: 'versova', name: 'Versova', city: 'Versova', state: 'Maharashtra', postalCode: '400061', lat: 19.1292, lng: 72.8143, description: 'Premium escorts in Versova, Andheri available 24/7.', reviewCount: 86, areas: ['Versova Beach', 'Andheri West', '7 Bungalows', 'Four Bungalows'] },
  { slug: 'vidyavihar', name: 'Vidyavihar', city: 'Vidyavihar', state: 'Maharashtra', postalCode: '400086', lat: 19.0906, lng: 72.9105, description: 'Premium escorts in Vidyavihar available 24/7.', reviewCount: 55, areas: ['Vidyavihar East', 'Vidyavihar West', 'Kanjurmarg', 'Bhandup'] },
  { slug: 'vijayawada', name: 'Vijayawada', city: 'Vijayawada', state: 'Andhra Pradesh', postalCode: '520001', lat: 16.5062, lng: 80.6480, description: 'Premium escorts in Vijayawada available 24/7.', reviewCount: 103, areas: ['Benz Circle', 'Labbipet', 'MG Road', 'Governor Pet'] },
  { slug: 'vikhroli', name: 'Vikhroli', city: 'Vikhroli', state: 'Maharashtra', postalCode: '400083', lat: 19.1053, lng: 72.9297, description: 'Premium escorts in Vikhroli available 24/7.', reviewCount: 69, areas: ['Vikhroli East', 'Vikhroli West', 'Kanjurmarg', 'Ghatkopar Link Road'] },
  { slug: 'vile-parle', name: 'Vile Parle', city: 'Vile Parle', state: 'Maharashtra', postalCode: '400057', lat: 19.0990, lng: 72.8461, description: 'Premium escorts in Vile Parle available 24/7.', reviewCount: 101, areas: ['Vile Parle East', 'Vile Parle West', 'Vileparle Station', 'Santa Cruz Airport'] },
  { slug: 'virar', name: 'Virar', city: 'Virar', state: 'Maharashtra', postalCode: '401303', lat: 19.4644, lng: 72.8059, description: 'Premium escorts in Virar available 24/7.', reviewCount: 82, areas: ['Virar East', 'Virar West', 'Nalasopara', 'Vasai Road'] },
  { slug: 'visakhapatnam', name: 'Visakhapatnam', city: 'Visakhapatnam', state: 'Andhra Pradesh', postalCode: '530001', lat: 17.6868, lng: 83.2185, description: 'Premium escorts in Visakhapatnam available 24/7.', reviewCount: 121, areas: ['Dwaraka Nagar', 'MVP Colony', 'Maddilapalem', 'Gajuwaka'] },
  { slug: 'wadala', name: 'Wadala', city: 'Wadala', state: 'Maharashtra', postalCode: '400037', lat: 19.0220, lng: 72.8626, description: 'Premium escorts in Wadala available 24/7.', reviewCount: 81, areas: ['Wadala East', 'Wadala West', 'GTB Nagar', 'Sewree'] },
  { slug: 'worli', name: 'Worli', city: 'Worli', state: 'Maharashtra', postalCode: '400018', lat: 19.0093, lng: 72.8165, description: 'Premium escorts in Worli available 24/7. Near Bandra-Worli Sea Link.', reviewCount: 156, areas: ['Worli Village', 'Worli Sea Face', 'Annie Besant Road', 'Century Mill'] },
];

export const locationSlugs = locations.map((l) => l.slug);

export function getLocationBySlug(slug: string): LocationData | undefined {
  return locations.find((l) => l.slug === slug);
}

export const services = [
  { slug: 'vip-escorts', name: 'VIP Escorts', icon: '👑', description: 'Elite VIP escorts with premium companionship experience.' },
  { slug: 'russian-escorts', name: 'Russian Escorts', icon: '🌹', description: 'Beautiful Russian and European escort models.' },
  { slug: 'independent-escorts', name: 'Independent Escorts', icon: '🌟', description: 'Verified independent escorts with genuine profiles.' },
  { slug: 'model-escorts', name: 'Model Escorts', icon: '💋', description: 'Professional model escorts and fashion companions.' },
  { slug: 'college-girls-escorts', name: 'College Girls Escorts', icon: '🎓', description: 'Young college girl companions, 18-25 years.' },
  { slug: 'celebrity-escorts', name: 'Celebrity Escorts', icon: '⭐', description: 'High-profile celebrity and Bollywood companions.' },
  { slug: 'air-hostess-escorts', name: 'Air Hostess Escorts', icon: '✈️', description: 'Professional air hostess escorts and flight attendants.' },
  { slug: 'house-wife-escorts', name: 'Housewife Escorts', icon: '🏠', description: 'Mature housewife escorts with warm companionship.' },
  { slug: 'high-profile-escorts', name: 'High Profile Escorts', icon: '💎', description: 'Exclusive high-profile companions for elite clients.' },
  { slug: 'north-indian-escorts', name: 'North Indian Escorts', icon: '🏔️', description: 'Beautiful North Indian escort companions.' },
  { slug: 'south-indian-escorts', name: 'South Indian Escorts', icon: '🌴', description: 'Gorgeous South Indian escort companions.' },
  { slug: 'punjabi-escorts', name: 'Punjabi Escorts', icon: '🌾', description: 'Vibrant Punjabi escort companions.' },
  { slug: 'bengali-escorts', name: 'Bengali Escorts', icon: '🌸', description: 'Beautiful Bengali escort companions.' },
  { slug: 'gujarati-escorts', name: 'Gujarati Escorts', icon: '🎪', description: 'Charming Gujarati escort companions.' },
  { slug: 'marathi-escorts', name: 'Marathi Escorts', icon: '🏯', description: 'Local Marathi escort companions.' },
  { slug: 'bdsm-escorts', name: 'BDSM Escorts', icon: '🔒', description: 'Professional BDSM dominatrix and submissive escorts.' },
  { slug: 'female-model-escorts', name: 'Female Model Escorts', icon: '👸', description: 'Top female model escorts across Mumbai.' },
  { slug: 'mumbai-escorts', name: 'Mumbai Escorts', icon: '🌆', description: 'Premium escorts across all of Mumbai.' },
  { slug: 'nepali-escorts', name: 'Nepali Escorts', icon: '🏔️', description: 'Beautiful Nepali escort companions.' },
  { slug: 'muslim-escorts', name: 'Muslim Escorts', icon: '🌙', description: 'Muslim escort companions available 24/7.' },
  { slug: 'marwadi-escorts', name: 'Marwadi Escorts', icon: '🎭', description: 'Charming Marwadi escort companions.' },
  { slug: 'horny-escorts', name: 'Horny Escorts', icon: '🔥', description: 'Passionate escort companions in Mumbai.' },
  { slug: 'girlfriends-escorts', name: 'Girlfriend Escorts', icon: '💕', description: 'GFE (Girlfriend Experience) escort companions.' },
  { slug: 'lesbian-escorts', name: 'Lesbian Escorts', icon: '🌈', description: 'Lesbian escort companions and couples.' },
  { slug: 'jaat-escorts', name: 'Jaat Escorts', icon: '🌟', description: 'Jaat escort companions in Mumbai.' },
  { slug: 'role-play-escorts', name: 'Role Play Escorts', icon: '🎭', description: 'Role play escort companions for fantasy experiences.' },
  { slug: 'bollywood-actress-escorts', name: 'Bollywood Actress Escorts', icon: '🎬', description: 'Bollywood actress lookalike escort companions.' },
  { slug: 'unsatisfied-bhabhi', name: 'Unsatisfied Bhabhi', icon: '💔', description: 'Mature Bhabhi escort companions.' },
  { slug: 'unsatisfied-female', name: 'Unsatisfied Female', icon: '💫', description: 'Passionate female escort companions.' },
  { slug: 'hj-bj-escorts', name: 'HJ BJ Escorts', icon: '✨', description: 'Special service escort companions in Mumbai.' },
];

export const serviceSlugs = services.map((s) => s.slug);

export function getServiceBySlug(slug: string) {
  return services.find((s) => s.slug === slug);
}

export const defaultFAQs = (location: string) => [
  {
    question: `How to book escorts in ${location}?`,
    answer: `Booking escorts in ${location} is simple! Call us at +91 90389 76363. Browse our verified profiles, select your preferred escort, confirm timing and location (incall/outcall), and make payment. We provide instant confirmation and 24/7 availability.`,
  },
  {
    question: `Are escorts in ${location} safe and verified?`,
    answer: `Yes! All our ${location} escorts are 100% verified with real photos, genuine profiles, and background checks. We ensure complete safety, discretion, and confidentiality. No fake profiles or bait-and-switch.`,
  },
  {
    question: `What types of escorts are available in ${location}?`,
    answer: `We offer all types: VIP escorts, independent escorts, Russian escorts, model escorts, college girls, celebrity escorts, air hostess, housewife escorts, and more. Regional options include North Indian, South Indian, Punjabi, Bengali, Marathi, Gujarati escorts.`,
  },
  {
    question: `What are the prices for escorts in ${location}?`,
    answer: `Pricing ranges from budget-friendly to premium VIP options. Independent escorts start from affordable rates while VIP and celebrity escorts are premium. Contact us for detailed pricing and special packages. No hidden charges - transparent pricing only.`,
  },
  {
    question: `Which areas in ${location} do you cover?`,
    answer: `We cover all ${location} areas for both incall and outcall services 24/7. Same-day booking with express service for urgent requests. Advance booking recommended for premium services.`,
  },
  {
    question: `Is your escorts service discreet and confidential?`,
    answer: `Absolutely! We maintain 100% discretion and confidentiality. Your personal information, booking details, and communications are completely private and secure. Our escorts are trained professionals who value privacy.`,
  },
  {
    question: `Do you provide incall and outcall services?`,
    answer: `Yes! We offer both incall and outcall services. Our escorts can visit your hotel, home, or any private location (outcall), or you can visit their luxurious apartments (incall). Both options are safe, clean, and comfortable.`,
  },
  {
    question: `Are the photos of escorts real?`,
    answer: `Yes, all photos are 100% genuine and verified. We maintain strict authenticity standards with no fake or stolen pictures. What you see is exactly what you get. If any escort doesn't match their profile photos, we offer free replacement or full refund.`,
  },
  {
    question: `What payment methods do you accept?`,
    answer: `We accept: cash payment (most preferred), online bank transfers, UPI payments (PhonePe, Google Pay, Paytm), and digital wallets. Payment is typically collected at the time of service.`,
  },
  {
    question: `Can I book escorts for overnight stays?`,
    answer: `Absolutely! We offer overnight bookings, weekend packages, and multi-day arrangements. Special discounted rates available for overnight and extended bookings. Advance booking recommended for overnight services.`,
  },
  {
    question: `How quickly can you arrange escorts?`,
    answer: `We offer same-day booking with delivery within 30-60 minutes depending on your location and availability. For immediate requirements, we provide express service for urgent bookings.`,
  },
  {
    question: `Do you offer couple or group bookings?`,
    answer: `Yes! We provide couple escorts for threesome experiences, group bookings for parties and events, and multiple escorts for bachelor parties. Contact us with your requirements for customized group packages.`,
  },
];
